import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import { Box, Divider, Stack, Typography } from '@mui/material';
import { useTheme } from '@emotion/react';

export default function Home() {
  const theme = useTheme();
  return (
    <>
      <Head>
        <title>Titabe - Inicio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Stack
          direction={{ xs: 'column', xl: 'row' }}
          spacing={5}
          justifyContent='center'
          alignItems='center'
          divider={<Divider orientation='vertical' flexItem />}
        >
          <Box
            sx={{
              justifyContent: 'flex-start',
              display: 'flex',
              color: theme.palette.primary.main,
              bgcolor: theme.palette.secondary.main,
              px: '15px',
            }}
          >
            <Typography variant='h1' fontWeight={700} fontSize='190px'>
              TITABE
            </Typography>
          </Box>
          <Box sx={{ minWidth: '50%' }}>
            <Typography variant='body1'>
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eius
              explicabo, eaque placeat omnis, soluta ipsa architecto iste neque
              labore eos reprehenderit dolore et dignissimos at consequuntur
              saepe necessitatibus ullam cupiditate!
            </Typography>
          </Box>
        </Stack>
      </main>
    </>
  );
}
